#files need to be moved to server/container which is running databases
#example:
#docker cp "C:\Users\pit\Google Drive\Udacity\Capstone Project\crypto-markets.csv" <CONTAINER ID>:/crypto-markets.csv

#connect to psql
 psql -h [HOST] --port=5432 -U postgres --dbname=cnn

#run in psql
\c cnn

\copy ccy_rates_stage FROM './currency_exchange_rates_02-01-1995_-_02-05-2018.csv' DELIMITER ',' CSV HEADER;

\copy ccy_crypto_stage FROM './crypto-markets.csv' DELIMITER ',' CSV HEADER;
